-- +goose Up
CREATE SCHEMA IF NOT EXISTS graveyard;
CREATE EXTENSION IF NOT EXISTS pgcrypto CASCADE;
CREATE EXTENSION IF NOT EXISTS pgjwt CASCADE;

-- +goose Down
DROP EXTENSION IF EXISTS pgjwt;
DROP EXTENSION IF EXISTS pgcrypto;
DROP SCHEMA IF EXISTS graveyard CASCADE;
