-- +goose Up
CREATE ROLE authenticator LOGIN NOINHERIT NOCREATEDB NOCREATEROLE NOSUPERUSER;
CREATE ROLE anonymous NOLOGIN;
CREATE ROLE submitter NOLOGIN;
CREATE ROLE admin NOLOGIN;

-- +goose Down
DROP ROLE IF EXISTS admin;
DROP ROLE IF EXISTS submitter;
DROP ROLE IF EXISTS anonymous;
DROP ROLE IF EXISTS authenticator;
